### ISSUE TITLE
observe_cloudwatch_logs_subscription.aws_lambda_function.lambda does not inherit tags

### ISSUE THREAD

**Issue by jkinkead** [observeinc/terraform-aws-collection#32]
The resource `observe_cloudwatch_logs_subscription.aws_lambda_function.lambda` created by this module does not inherit tags passed in via the `tags` variable.

It looks like [this is not passed in](https://github.com/observeinc/terraform-aws-collection/blob/17ba05f34c95bdb57f892a1111b91510c94e8509/subscription.tf) anywhere to the child module, and also that [the child module does not support tags](https://github.com/observeinc/terraform-aws-cloudwatch-logs-subscription/blob/6aa9cb396b24445330c0216b6b915c0e3da8b48e/variables.tf).

**Comment by luke-zhu** [comment]
Thanks for bring this up, I've created a few commits to potentially unblock things.

I believe we do not pass the `tags` variable into a lot of things in this repo (cloutrails, eventbridge rules, etc.). So, a solution that may work is better https://registry.terraform.io/providers/hashicorp/aws/latest/docs#default_tags-configuration-block. We haven't documented it but it seems like a more reliable yet flexible-enough way to pass in tags.

To do so, you would do something like this:
```
provider "aws" {
  default_tags {
    tags = {
      Environment = "Test"
      Name        = "Provider Tag"
    }
  }
}
```

If you want different tags per module, you could do something like this

```
provider "aws" {
  default_tags {
    tags = {
      Key1 = "Value1"
    }
  }
 alias = "first"
}

provider "aws" {
  default_tags {
    tags = {
      Key2 = "Value2"
    }
  }
 alias = "second"
}

module "first" {
  providers = {
    aws = aws.first
  }
}

module "second" {
  aws = aws.second
}
```

**Comment by jkinkead** [comment]
Thanks for the workaround suggestion.

I don't that will work for my case, because we have shared providers across a large infrastructure project - and I don't think there's a way to inherit provider configuration from another provider? I'm a Terraform novice, so I might just be missing something.

**Comment by luke-zhu** [comment]
Hi, the commit for passing tags made it into this release: https://github.com/observeinc/terraform-aws-collection/releases/tag/v1.2.2

I've filed a bug internally for passing tags to (almost) all Observe terraform resources.
